// "use client"
import './globals.css';
import { AppProviders } from './reduxProvider';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icon: { apple: '/icon.png' },
  themeColor: "#fff"
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>
          {children}
        </AppProviders>
      </body>
    </html>
  )
}
